/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Colegio;
import static Colegio.conexion.conexion;
import static Colegio.conexion.getConexion;
import java.sql.*;
import java.util.Scanner;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Usuario
 */
public class Ingreso extends javax.swing.JFrame {
 conexion con = new conexion();
  DefaultTableModel modelo= new DefaultTableModel();
 //Connection cn = conexion.conexion;
 
  
   void limpiar_tb(){
         
       DefaultTableModel tb = (DefaultTableModel) tb_alumnos.getModel();
        int a = tb_alumnos.getRowCount()-1;
        for (int i = a; i >= 0; i--) {          
        tb.removeRow(tb.getRowCount()-1);
        }
            
             }
   
void mostrar_datos(){

    //tb_alumnos.setModel(modelo);
    //String sql= "SELECT * FROM alumnos";
    //String []datos = new String [5];
        try {
         DefaultTableModel modeloC = (DefaultTableModel) tb_alumnos.getModel();
          String sql2="select * from alumnos order by id_alumno";
             CallableStatement cmd2=con.getConexion().prepareCall(sql2);
            ResultSet rs= cmd2.executeQuery();
 
            while(rs.next()){
 
               Object[] datos=new Object[100];
              
                  for(int i=0;i<5;i++){
                 
                    datos[i]=rs.getString(i+1);
                  
  //JOptionPane.showMessageDialog(null, datos[i]);
                }
            
               modeloC.addRow(datos);
            }
            
            //tb_alumnos.setModel(modeloC1);
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    /**
     * Creates new form Ingreso
     */
    public Ingreso() {
        initComponents();
        limpiar_tb();
        mostrar_datos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        Curso = new javax.swing.JTextField();
        Cali = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_alumnos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 219, -1, -1));

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 219, -1, -1));

        jButton4.setText("Salir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 248, 66, -1));

        jButton5.setText("Editar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 219, -1, -1));

        jLabel1.setText("Nombre del alumno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 28, -1, -1));

        jLabel2.setText("Apellido del alumno");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, -1, -1));

        jLabel4.setText("Calificacion");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        Apellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 73, 113, -1));

        Curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CursoActionPerformed(evt);
            }
        });
        getContentPane().add(Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 113, 113, -1));

        Cali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaliActionPerformed(evt);
            }
        });
        getContentPane().add(Cali, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 168, 113, -1));

        Nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreActionPerformed(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 29, 113, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 219, -1, -1));

        jLabel5.setText("Datos del alumno");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 11, -1, 38));

        jLabel3.setText("Curso");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        tb_alumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Curso", "Calificacion"
            }
        ));
        jScrollPane1.setViewportView(tb_alumnos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 51, 256, 160));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Formulario_ingreso\\src\\Colegio\\conectar-con-los-alumnos.jpg")); // NOI18N
        jLabel6.setText("jLabel3");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 570, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            int fila = tb_alumnos.getSelectedRow()+1;
         
     String filac = String.valueOf(fila);
     if (fila!=0){
    try{
            String sql ="delete from alumnos where id_alumno = '"+filac+"'";
             CallableStatement cmd=con.getConexion().prepareCall(sql);
            cmd.executeUpdate();
            
  
   
   
   Nombre.setText(" ");
    Apellido.setText(" ");
     Curso.setText(" ");
      Cali.setText(" ");
                 
       limpiar_tb();
       mostrar_datos();
       
       
     }catch (Exception e) {
 
            System.out.println(e.getMessage());
 
        }  
        } else{
         JOptionPane.showMessageDialog(null,"selecciona una fila");
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int fila = tb_alumnos.getSelectedRow()+1;
     
  String nombre =  Nombre.getText();
    String nit =  Apellido.getText();
      String tel =  Curso.getText();
        String dir =  Cali.getText();
         //JOptionPane.showMessageDialog(null, fila);
     String filac = String.valueOf(fila);
     if (fila!=0){
    try{
            String sql ="update alumnos set Nombre = '"+nombre+"',Apellido = '"+nit+"'"
                    + ",Curso = '"+dir+"', Calificacion = '"+tel+"' where id_alumno = "+filac+"";
                    
             CallableStatement cmd=con.getConexion().prepareCall(sql);
            cmd.executeUpdate();
            
  
 

   Nombre.setText(" ");
    Apellido.setText(" ");
      Curso.setText(" ");
       Cali.setText(" ");
                 
      limpiar_tb();
        mostrar_datos();
       
       
     }catch (Exception e) {
 
            System.out.println(e.getMessage());
 
        }  
     } else{
         JOptionPane.showMessageDialog(null,"selecciona una fila");
         }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void ApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoActionPerformed

    private void CursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CursoActionPerformed

    private void CaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaliActionPerformed

    private void NombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
       
        
        String nombre = Nombre.getText();
        String ape = Apellido.getText();
        String curso = Curso.getText();
        String cali = Cali.getText();
      
            
          
            PreparedStatement enrollItmt;
            /*
        if (con.conexion == null){
            getConexion();
        }*/
     try {
        
         enrollItmt = con.getConexion().prepareStatement("INSERT INTO alumnos(nombres, apellidos,curso,calificacion) VALUES (?,?,?,?)");
       
        enrollItmt.setString(1,Nombre.getText());
        enrollItmt.setString(2,Apellido.getText());
        enrollItmt.setString(3,Curso.getText());
        enrollItmt.setString(4,Cali.getText());
         //String sSQL = "INSERT INTO alumnos(nombres, apellidos,curso,calificacion) VALUES (?,?,?,?)";
         
        //Statement st = (Statement) cn.createStatement();
        //st.executeUpdate(sSQL);
         enrollItmt.executeUpdate();
         //JOptionPane.showMessageDialog(null, "Datos guardados");
         limpiar_tb();
         mostrar_datos();
    } catch (SQLException ex) {
         Logger.getLogger(Ingreso.class.getName()).log(Level.SEVERE, null, ex);
     }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Cali;
    private javax.swing.JTextField Curso;
    private javax.swing.JTextField Nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_alumnos;
    // End of variables declaration//GEN-END:variables
}
